In [6]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process as fuzz_process

# import os
# import warnings

# import numpy as np

import pickle
import pandas as pd
# pd.set_option("display.max_columns", 50)
import matplotlib.pyplot as plt
%matplotlib inline
# import networkx as nx

# from . import utils
# import utils
from utils import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
df_stops = filter_stops_by_distance_from_zurich_hb(load_df_stops(), 15000)
df_stops

                             stop_name   latitude  longitude
stop_id
176             Zimmerberg-Basistunnel  47.351678   8.521958
8500926    Oetwil a.d.L., Schweizäcker  47.423627   8.403183
8502075  Zürich Flughafen, Carterminal  47.451024   8.563729
8502186           Dietikon Stoffelbach  47.393327   8.398960
8502186           Dietikon Stoffelbach  47.393400   8.398942
...                                ...        ...        ...
8503088                  Zürich HB SZU  47.377391   8.539358
8503307                    Bassersdorf  47.438570   8.626225
8583870                    Bahnhof Süd  47.357174   8.437013
8590279                Shopping Center  47.420448   8.368517
8590464                        Bahnhof  47.311781   8.524311

[1626 rows x 3 columns]

In [9]:
fuzzy_search_stops(df_stops, 'Zürich Heur')
# fuzzy_search_stops(df_stops, 'Zürich Trie')
# fuzzy_search_stops(df_stops, 'Weiningen')
# fuzzy_search_stops(df_stops, 'Bremgarden')

                   stop_name   latitude  longitude  ratio
stop_id
8591190      Zürich, Heuried  47.369410   8.506354     85
8503000            Zürich HB  47.378176   8.540212     80
8591427         Zürich, Werd  47.372324   8.526845     78
8591191      Zürich, Himmeri  47.419877   8.538657     77
8591200   Zürich, Holzerhurd  47.423803   8.496616     76
...                      ...        ...        ...    ...
8503097     Langnau-Gattikon  47.287309   8.543832      7
8502222  Bonstetten-Wettswil  47.325903   8.468194      7
8502758                 Post  47.244748   8.532980      0
8502758                 Post  47.244748   8.532971      0
8503062                  Egg  47.301499   8.689610      0

[1626 rows x 4 columns]

In [ ]:
# connections_df = utils.load_stop_times()
# edges_df = connections_df[['dep_stop_id', 'arr_stop_id']]
# edges_df = edges_df.drop_duplicates()
# edges_df
# edges_df.merge(df_stops, left_on='dep_stop_id', right_on='stop_id')

In [17]:
# df_walks = pd.read_csv(PATH_WALK_EDGES_15K)

df_walks = filter_connections_by_stops(load_df_walks(), df_stops)
df_walks

     dep_stop_id  weight  arr_stop_id
0        8503000     137      8503088
1        8503000     169      8503446
2        8503000     409      8503499
3        8503000     587      8503500
4        8503000     147      8587348
..           ...     ...          ...
394      8591427     272      8591079
395      8591427     554      8591184
396      8591427     572      8591218
397      8591427     373      8591227
398      8591427     263      8591381

[399 rows x 3 columns]