In [1]:

import pandas as pd
# pd.set_option("display.max_rows",40)
# pd.set_option("display.max_columns", 100)
import matplotlib.pyplot as plt
%matplotlib inline

from utils import *
from algo import *
from visualization import *

%load_ext autoreload
%autoreload 2

_____

In [2]:
df_stops = filter_stops_by_distance_from_zurich_hb(decompress_pickle(PATH_STOPS_15K_PBZ2), STOPS_RADIUS)
df_walks = filter_connections_by_stops(decompress_pickle(PATH_WALK_EDGES_15K_PBZ2), df_stops)
df_conns = filter_connections_by_stops(decompress_pickle(PATH_CONNECTIONS_PBZ2), df_stops)
dfs = (df_stops, df_walks, df_conns)

In [3]:
END_TIME = Time(h=10).in_seconds()
END_ID = ZURICH_HB_ID
START_ID = ZURICH_WERD_ID
# START_ID = 8502186
DAY_OF_WEEK = 1     # Val

# routes_data = generate_routes(dfs, START_ID, END_ID, END_TIME, DAY_OF_WEEK, min_confidence=0.8, verbose=True)

for route_cost, cum_proba, df_route in generate_routes_gen(dfs, START_ID, END_ID, END_TIME, DAY_OF_WEEK, min_confidence=0.8, nroutes=1, verbose=True):
    display(df_route)
    # display(print_directions(df_route, '<end-stop-name>'))

Starting routing
Iteration: 1 - Found routes: 1
Probability: 0.9999800287545476
Route cost: 1104.0
---------------------------------------------

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s,weight,proba
6333,walk,8591427,8503011,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,444.0,1.0
59615,82.TA.26-8-A-j19-1.50.R,8503011,8503000,Zürich Wiedikon,Zürich HB,21.565064,96.656222,zug,Winterthur,8,35340.0,35580.0,660,0.99998

-----

In [4]:
df_stops

                             stop_name   latitude  longitude
stop_id
176             Zimmerberg-Basistunnel  47.351678   8.521958
8500926    Oetwil a.d.L., Schweizäcker  47.423627   8.403183
8502075  Zürich Flughafen, Carterminal  47.451024   8.563729
8502186           Dietikon Stoffelbach  47.393327   8.398960
8502187         Rudolfstetten Hofacker  47.364670   8.376952
...                                ...        ...        ...
8596007           Schlieren, Geissweid  47.397815   8.444236
8596008           Zürich, Hermetschloo  47.394148   8.473889
8596100       Bassersdorf, Sportanlage  47.444464   8.610711
8596113        Dübendorf, Hochbord Süd  47.399006   8.600462
8596126            Zürich, Bus Station  47.381066   8.537301

[1588 rows x 3 columns]

In [5]:
# df_conns[df_conns['trip_id'] == '25.TA.26-4-A-j19-1.3.H']
df_conns

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,dayofweek,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s
0,279.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,28080,28080
1,193.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,54960,55020
2,224.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,47760,47820
3,225.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,24480,24480
4,223.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,63180,63180
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129695,2.TA.6-E02-j19-1.2.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E02,35700,36600
2129696,5.TA.5-E03-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E03,73500,74400
2129697,2.TA.6-E01-j19-1.2.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"St. Gallen, Lagerstrasse/Bhf",E01,77700,78900
2129698,5.TA.6-E02-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E02,68700,69600
2129699,4.TA.5-E03-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E03,45600,46500

In [6]:
df_walks

      arr_stop_id  dep_stop_id  weight
0         8503086          176     507
1         8591392          176     686
2         8590616      8500926     267
3         8590737      8500926     480
4         8503016      8502075     267
...           ...          ...     ...
6805      8587348      8596126     662
6806      8591071      8596126     613
6807      8591282      8596126     376
6808      8591368      8596126     281
6809      8591379      8596126     627

[6810 rows x 3 columns]