In [6]:

import pickle
import pandas as pd
# pd.set_option("display.max_rows",40)
# pd.set_option("display.max_columns", 100)
import matplotlib.pyplot as plt
%matplotlib inline

from utils import *
from algo import *

from scipy.stats import norm

%load_ext autoreload
%autoreload 2

/Users/mroust/Library/Mobile Documents/com~apple~CloudDocs/code/lab-ds/stochastic-journey-planner/routing/algo.py:22: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  #===============================================================

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

_____

In [7]:
END_TIME = Time(h=10).in_seconds()      # Desired arrival time
START_ID = ZURICH_WERD_ID              # Departure station_id
# START_ID = ZURICH_HEURIED_ID
# START_ID = DIETIKON_ID

END_ID = ZURICH_HB_ID                   # Destination station_id
# END_ID = DIETIKON_ID

DAY_OF_WEEK = 1                         # Value 1-7. Monday=1, Tuesday=2,...
MIN_CONFIDENCE = 0.8                    # Min required confidence/probability of making all the connections of journey
N_ROUTES = 3                            # N best journey's to output

In [8]:
# Probabilistic Yen's algorithm. verbose=True will output routes as they are found
routes_data = generate_routes(START_ID, END_ID, END_TIME, DAY_OF_WEEK, MIN_CONFIDENCE, N_ROUTES, verbose=True)

Starting routing
Iteration: 1 - Found routes: 1
Probability: 0.8109142650448815
Route cost: 2952.0

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s,weight,proba
7,walk,8502186,8502270,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,672.0,1.0
7132,25.TA.1-17-A-j19-1.6.H,8502270,8517376,Bergfrieden,Dietikon Schöneggstrasse,98.993483,83.292671,zug,Dietikon,17,33720.0,33780.0,60.0,1.0
193083,25.TA.1-17-A-j19-1.6.H,8517376,8503508,Dietikon Schöneggstrasse,Dietikon,77.33082,208.225405,zug,Dietikon,17,33780.0,33960.0,660.0,0.97309
153015,55.TA.26-19-j19-1.16.H,8503508,8503001,Dietikon,Zürich Altstetten,62.722605,79.820627,zug,Effretikon,19,34440.0,34740.0,720.0,0.999996
44965,468.TA.26-5-A-j19-1.209.R,8503001,8503020,Zürich Altstetten,Zürich Hardbrücke,73.527212,65.575162,zug,Pfäffikon SZ,5,35160.0,35280.0,540.0,1.0
62612,352.TA.26-6-A-j19-1.75.H,8503020,8503000,Zürich Hardbrücke,Zürich HB,35.944248,86.887569,zug,Uetikon,6,35700.0,35880.0,300,0.833343

---------------------------------------------
Iteration: 2 - Found routes: 2
Probability: 0.9989269543732909
Route cost: 2952.0

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s,weight,proba
7,walk,8502186,8502270,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,672.0,1.0
7132,25.TA.1-17-A-j19-1.6.H,8502270,8517376,Bergfrieden,Dietikon Schöneggstrasse,98.993483,83.292671,zug,Dietikon,17,33720.0,33780.0,60.0,1.0
193083,25.TA.1-17-A-j19-1.6.H,8517376,8503508,Dietikon Schöneggstrasse,Dietikon,77.33082,208.225405,zug,Dietikon,17,33780.0,33960.0,900.0,0.998927
153122,57.TA.26-36-j19-1.28.R,8503508,8503001,Dietikon,Zürich Altstetten,62.722605,79.820627,zug,Zürich Flughafen,36,34680.0,34980.0,360.0,1.0
43415,57.TA.26-36-j19-1.28.R,8503001,8503000,Zürich Altstetten,Zürich HB,29.441598,75.444891,zug,Zürich Flughafen,36,35040.0,35340.0,960,1.0

---------------------------------------------
Iteration: 3 - Found routes: 3
Probability: 0.978487621369643
Route cost: 3310

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s,weight,proba
9,walk,8502186,8590203,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,670,1.0
642079,201.TA.1-305-j19-1.2.R,8590203,8590220,"Bergdietikon, Dünni","Dietikon, Marmori-Weiher",59.54485,183.467602,bus,"Dietikon, Bahnhof",305,33360.0,33420.0,60,1.0
645007,201.TA.1-305-j19-1.2.R,8590220,8590223,"Dietikon, Marmori-Weiher","Dietikon, Stadthaus",77.33082,208.225405,bus,"Dietikon, Bahnhof",305,33420,33480,560.0,0.978488
2662,walk,8590223,8503508,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,700.0,1.0
153122,57.TA.26-36-j19-1.28.R,8503508,8503001,Dietikon,Zürich Altstetten,62.722605,79.820627,zug,Zürich Flughafen,36,34680.0,34980.0,360.0,1.0
43415,57.TA.26-36-j19-1.28.R,8503001,8503000,Zürich Altstetten,Zürich HB,29.441598,75.444891,zug,Zürich Flughafen,36,35040.0,35340.0,960,1.0

---------------------------------------------

-----

In [3]:
df_stops

                             stop_name   latitude  longitude
stop_id
176             Zimmerberg-Basistunnel  47.351678   8.521958
8500926    Oetwil a.d.L., Schweizäcker  47.423627   8.403183
8502075  Zürich Flughafen, Carterminal  47.451024   8.563729
8502186           Dietikon Stoffelbach  47.393327   8.398960
8502187         Rudolfstetten Hofacker  47.364670   8.376952
...                                ...        ...        ...
8596007           Schlieren, Geissweid  47.397815   8.444236
8596008           Zürich, Hermetschloo  47.394148   8.473889
8596100       Bassersdorf, Sportanlage  47.444464   8.610711
8596113        Dübendorf, Hochbord Süd  47.399006   8.600462
8596126            Zürich, Bus Station  47.381066   8.537301

[1588 rows x 3 columns]

In [4]:
# df_conns[df_conns['trip_id'] == '25.TA.26-4-A-j19-1.3.H']
df_conns

,trip_id,dep_stop_id,arr_stop_id,dep_stop_name,arr_stop_name,mean,std,dayofweek,transport_name,trip_headsign,route_short_name,dep_time_s,arr_time_s
0,279.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,28080,28080
1,193.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,54960,55020
2,224.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,47760,47820
3,225.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,24480,24480
4,223.TA.26-301-j19-1.3.R,8500926,8590737,"Oetwil a.d.L., Schweizäcker","Oetwil an der Limmat, Halde",77.33082,208.225405,1,bus,"Oetwil an der Limmat, Post",301,63180,63180
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129695,2.TA.6-E02-j19-1.2.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E02,35700,36600
2129696,5.TA.5-E03-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E03,73500,74400
2129697,2.TA.6-E01-j19-1.2.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"St. Gallen, Lagerstrasse/Bhf",E01,77700,78900
2129698,5.TA.6-E02-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E02,68700,69600
2129699,4.TA.5-E03-j19-1.4.R,8596126,8573205,"Zürich, Bus Station","Zürich Flughafen, Bahnhof",77.33082,208.225405,7,bus,"Zürich Flughafen, Bahnhof",E03,45600,46500

In [5]:
df_walks

      arr_stop_id  dep_stop_id  weight
0         8503086          176     507
1         8591392          176     686
2         8590616      8500926     267
3         8590737      8500926     480
4         8503016      8502075     267
...           ...          ...     ...
6805      8587348      8596126     662
6806      8591071      8596126     613
6807      8591282      8596126     376
6808      8591368      8596126     281
6809      8591379      8596126     627

[6810 rows x 3 columns]